# Generated by Django 3.2.8 on 2021-10-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalapi', '0002_ksp_standard_pool_pool_token_reward_reward_code_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ksp_Standard',
            new_name='KspStandard',
        ),
        migrations.RenameModel(
            old_name='Pool_Token',
            new_name='PoolToken',
        ),
        migrations.RenameModel(
            old_name='Reward_Code',
            new_name='RewardCode',
        ),
        migrations.AddField(
            model_name='token',
            name='token_image',
            field=models.ImageField(blank=True, upload_to='token/'),
        ),
    ]
